# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class SafechainAgent < Formula
  desc "Aikido SafeChain Agent"
  homepage "https://github.com/AikidoSec/safechain-agent"
  version "0.1.0"
  license "AGPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/safechain-agent/releases/download/v#{version}/safechain-agent-darwin-amd64"
      sha256 "67e6894677d97debe03997975c315550320bf830afc2d8b2374ea1fa675f1526"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/safechain-agent/releases/download/v#{version}/safechain-agent-darwin-arm64"
      sha256 "cd31eb13190a9796d8ecd768db5324c4c9b19ba894f518b2fbd2d05e28590f5a"
    end
  end

  def install
    # Install Aikido Agent binary
    binary_name = Hardware::CPU.intel? ? "safechain-agent-darwin-amd64" : "safechain-agent-darwin-arm64"
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    bin.install downloaded_file => "safechain-agent"
    chmod 0755, bin/"safechain-agent"
  end

  service do
    name macos: "com.aikidosecurity.safechainagent"
    run [opt_bin/"safechain-agent"]
    run_at_load true
    keep_alive true
    log_path var/"log/safechain-agent.log"
    error_log_path var/"log/safechain-agent.error.log"
  end

  test do
    system "#{bin}/safechain-agent", "--version"
  end
end
