# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class ScAgent < Formula
  desc "Safechain agent daemon"
  homepage "https://github.com/tudor-timcu/sc-agent"
  version "pr-1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v1.5.0/sc-agent-darwin-amd64"
      sha256 "8fa20bd7db09bbb404a1c8bbf4df8253b88e705690f56d0469b9e3b792bcb805"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v1.5.0/sc-agent-darwin-arm64"
      sha256 "55238898f207e54c0820def1c7c289c84fb1cd7b8eae7e7c44280378a4ebaf65"
    end
  end

  def install
    binary_name = Hardware::CPU.intel? ? "sc-agent-darwin-amd64" : "sc-agent-darwin-arm64"
    
    # Try to find the file - Homebrew might have renamed it
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    
    bin.install downloaded_file => "sc-agent"
    chmod 0755, bin/"sc-agent"
  end

  service do
    run [opt_bin/"sc-agent"]
    keep_alive true
    log_path var/"log/sc-agent.log"
    error_log_path var/"log/sc-agent.error.log"
  end

  test do
    system "#{bin}/sc-agent", "--version"
  end
end

