# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class ScAgent < Formula
  desc "Safechain agent daemon"
  homepage "https://github.com/tudor-timcu/sc-agent"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v1.6.0/sc-agent-darwin-amd64"
      sha256 "287ddc7fae5bc011fca80b2fcd7f34a685ff55473d74eee1a8b7257087f6c4fc"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/sc-agent/releases/download/v1.6.0/sc-agent-darwin-arm64"
      sha256 "4577f86355a1ba07c4c935e863f47b30b6d0890f1bf8b560b7975b5317727db2"
    end
  end

  def install
    binary_name = Hardware::CPU.intel? ? "sc-agent-darwin-amd64" : "sc-agent-darwin-arm64"
    
    # Try to find the file - Homebrew might have renamed it
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    
    bin.install downloaded_file => "sc-agent"
    chmod 0755, bin/"sc-agent"
  end

  service do
    name macos: "com.aikidosecurity.sc-agent"
    run [opt_bin/"sc-agent"]
    run_at_load true
    keep_alive true
    require_root true
    log_path "/var/log/aikidosecurity/sc-agent.log"
    error_log_path "/var/log/aikidosecurity/sc-agent.error.log"
  end

  test do
    system "#{bin}/sc-agent", "--version"
  end
end

